import React from 'react';
import {Icon} from '@ui-kitten/components';

export const SearchIcon = (props: any) => (<Icon name='search-outline' {...props} />)
export const DarkIcon = (props: any) => (<Icon name='moon-outline' {...props} />)
export const LightIcon = (props: any) => (<Icon name='sun-outline' {...props} />)
export const ClosedIcon = (props: any) => (<Icon name='lock-outline' {...props} />)
export const CrossIcon = (props: any) => (<Icon name='close-outline' {...props} />)
export const NotClosedIcon = (props: any) => (<Icon name='unlock-outline' {...props} />)
export const AddIcon = (props: any) => (<Icon name='plus-outline' {...props} />)
export const OptionsIcon = (props: any) => (<Icon name='more-vertical-outline' {...props} />)
export const BackIcon = (props: any) => (<Icon name='arrow-back-outline' {...props} />)
export const PersonIcon = (props: any) => (<Icon name='person-outline' {...props} />)
export const PasswordIcon = (props: any) => (<Icon name='keypad-outline' {...props} />)
export const CalendarIcon = (props: any) => (<Icon name='calendar-outline' {...props}/>)
export const CheckIcon = (props: any) => (<Icon name='checkmark-outline' {...props}/>)
export const ChevronDownIcon = (props: any) => (<Icon name='chevron-down-outline' {...props}/>)
export const EditSignatureIcon = (props: any) => (<Icon name='edit-outline' {...props}/>)
export const EditIcon = (props: any) => (<Icon name='edit-2-outline' {...props}/>)
export const Camera = (props: any) => (<Icon name='camera-outline' {...props}/>)
export const AlertTriangle = (props: any) => (<Icon name='alert-triangle-outline' {...props}/>)
export const Printer = (props: any) => (<Icon name='printer-outline' {...props}/>)
export const ImageIcon = (props: any) => (<Icon name='image-outline' {...props}/>)
export const SyncIcon = (props: any) => (<Icon name='sync-outline' {...props}/>)
export const FilmIcon = (props: any) => (<Icon name='film-outline' {...props}/>)
export const TrashIcon = (props: any) => (<Icon name='trash-outline' {...props}/>)
