version: '3.4'

services:
  inspections.api:
    image: iosoft/scb-backend
    environment:
      - ConnectionStrings__Inspections=Server=aa1ma34symakg8u.cxfnhkwyyqmn.us-east-2.rds.amazonaws.com;Port=5432;Database=ReportsDb;User Id=appuser;Password=Smartcode123*;
      - ClientSettings__S3BucketName=cse-inspetions-dev-photos
      - AWS__Region=us-east-2
      - UIPORT=3000
    volumes:
      - ~/.aws/:/root/.aws:ro
    ports:
      - "80:80"
    
  inspections.ui:
    image: iosoft/scb-frontend
    environment:
      - BASE_URL=http://Chensengdev.eba-7qzmqmd2.us-east-2.elasticbeanstalk.com
    ports:
      - "3000:3000"
