/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CheckListItemDTO,
    CheckListItemDTOFromJSON,
    CheckListItemDTOFromJSONTyped,
    CheckListItemDTOToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddCheckListCommand
 */
export interface AddCheckListCommand {
    /**
     * 
     * @type {string}
     * @memberof AddCheckListCommand
     */
    text?: string | null;
    /**
     * 
     * @type {Array<CheckListItemDTO>}
     * @memberof AddCheckListCommand
     */
    items?: Array<CheckListItemDTO> | null;
    /**
     * 
     * @type {string}
     * @memberof AddCheckListCommand
     */
    annotation?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AddCheckListCommand
     */
    isConfiguration?: boolean;
}

export function AddCheckListCommandFromJSON(json: any): AddCheckListCommand {
    return AddCheckListCommandFromJSONTyped(json, false);
}

export function AddCheckListCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCheckListCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'text': !exists(json, 'text') ? undefined : json['text'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(CheckListItemDTOFromJSON)),
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'isConfiguration': !exists(json, 'isConfiguration') ? undefined : json['isConfiguration'],
    };
}

export function AddCheckListCommandToJSON(value?: AddCheckListCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'text': value.text,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(CheckListItemDTOToJSON)),
        'annotation': value.annotation,
        'isConfiguration': value.isConfiguration,
    };
}


