/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CheckValue,
    CheckValueFromJSON,
    CheckValueFromJSONTyped,
    CheckValueToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddCheckListItemCommand
 */
export interface AddCheckListItemCommand {
    /**
     * 
     * @type {number}
     * @memberof AddCheckListItemCommand
     */
    idCheckList?: number;
    /**
     * 
     * @type {string}
     * @memberof AddCheckListItemCommand
     */
    text?: string | null;
    /**
     * 
     * @type {CheckValue}
     * @memberof AddCheckListItemCommand
     */
    checked?: CheckValue;
    /**
     * 
     * @type {boolean}
     * @memberof AddCheckListItemCommand
     */
    editable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AddCheckListItemCommand
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AddCheckListItemCommand
     */
    remarks?: string | null;
}

export function AddCheckListItemCommandFromJSON(json: any): AddCheckListItemCommand {
    return AddCheckListItemCommandFromJSONTyped(json, false);
}

export function AddCheckListItemCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddCheckListItemCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idCheckList': !exists(json, 'idCheckList') ? undefined : json['idCheckList'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'checked': !exists(json, 'checked') ? undefined : CheckValueFromJSON(json['checked']),
        'editable': !exists(json, 'editable') ? undefined : json['editable'],
        'required': !exists(json, 'required') ? undefined : json['required'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
    };
}

export function AddCheckListItemCommandToJSON(value?: AddCheckListItemCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idCheckList': value.idCheckList,
        'text': value.text,
        'checked': CheckValueToJSON(value.checked),
        'editable': value.editable,
        'required': value.required,
        'remarks': value.remarks,
    };
}


