/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddNoteCommand
 */
export interface AddNoteCommand {
    /**
     * 
     * @type {number}
     * @memberof AddNoteCommand
     */
    reportId?: number;
    /**
     * 
     * @type {string}
     * @memberof AddNoteCommand
     */
    text?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AddNoteCommand
     */
    checked?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AddNoteCommand
     */
    needsCheck?: boolean;
}

export function AddNoteCommandFromJSON(json: any): AddNoteCommand {
    return AddNoteCommandFromJSONTyped(json, false);
}

export function AddNoteCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddNoteCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportId': !exists(json, 'reportId') ? undefined : json['reportId'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'checked': !exists(json, 'checked') ? undefined : json['checked'],
        'needsCheck': !exists(json, 'needsCheck') ? undefined : json['needsCheck'],
    };
}

export function AddNoteCommandToJSON(value?: AddNoteCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportId': value.reportId,
        'text': value.text,
        'checked': value.checked,
        'needsCheck': value.needsCheck,
    };
}


