/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PrintSectionStatus,
    PrintSectionStatusFromJSON,
    PrintSectionStatusFromJSONTyped,
    PrintSectionStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddPrintSectionCommand
 */
export interface AddPrintSectionCommand {
    /**
     * 
     * @type {string}
     * @memberof AddPrintSectionCommand
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddPrintSectionCommand
     */
    content?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AddPrintSectionCommand
     */
    description?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AddPrintSectionCommand
     */
    isMainReport?: boolean;
    /**
     * 
     * @type {PrintSectionStatus}
     * @memberof AddPrintSectionCommand
     */
    status?: PrintSectionStatus;
}

export function AddPrintSectionCommandFromJSON(json: any): AddPrintSectionCommand {
    return AddPrintSectionCommandFromJSONTyped(json, false);
}

export function AddPrintSectionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPrintSectionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'content': !exists(json, 'content') ? undefined : json['content'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'isMainReport': !exists(json, 'isMainReport') ? undefined : json['isMainReport'],
        'status': !exists(json, 'status') ? undefined : PrintSectionStatusFromJSON(json['status']),
    };
}

export function AddPrintSectionCommandToJSON(value?: AddPrintSectionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'content': value.content,
        'description': value.description,
        'isMainReport': value.isMainReport,
        'status': PrintSectionStatusToJSON(value.status),
    };
}


