/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EMALicense,
    EMALicenseFromJSON,
    EMALicenseFromJSONTyped,
    EMALicenseToJSON,
} from './';

/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    id?: number;
    /**
     * 
     * @type {Array<object>}
     * @memberof Address
     */
    readonly domainEvents?: Array<object> | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    addressLine?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    unit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    postalCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Address
     */
    licenseId?: number;
    /**
     * 
     * @type {EMALicense}
     * @memberof Address
     */
    license?: EMALicense;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'domainEvents': !exists(json, 'domainEvents') ? undefined : json['domainEvents'],
        'addressLine': !exists(json, 'addressLine') ? undefined : json['addressLine'],
        'addressLine2': !exists(json, 'addressLine2') ? undefined : json['addressLine2'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'licenseId': !exists(json, 'licenseId') ? undefined : json['licenseId'],
        'license': !exists(json, 'license') ? undefined : EMALicenseFromJSON(json['license']),
    };
}

export function AddressToJSON(value?: Address | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'addressLine': value.addressLine,
        'addressLine2': value.addressLine2,
        'unit': value.unit,
        'country': value.country,
        'postalCode': value.postalCode,
        'licenseId': value.licenseId,
        'license': EMALicenseToJSON(value.license),
    };
}


