/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordDto
 */
export interface ChangePasswordDto {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    currentPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    newPassword?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordDto
     */
    newPasswordConfirmation?: string | null;
}

export function ChangePasswordDtoFromJSON(json: any): ChangePasswordDto {
    return ChangePasswordDtoFromJSONTyped(json, false);
}

export function ChangePasswordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'currentPassword': !exists(json, 'currentPassword') ? undefined : json['currentPassword'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
        'newPasswordConfirmation': !exists(json, 'newPasswordConfirmation') ? undefined : json['newPasswordConfirmation'],
    };
}

export function ChangePasswordDtoToJSON(value?: ChangePasswordDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userName': value.userName,
        'currentPassword': value.currentPassword,
        'newPassword': value.newPassword,
        'newPasswordConfirmation': value.newPasswordConfirmation,
    };
}


