/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CheckListDisplay {
    Numbered = 'Numbered',
    Inline = 'Inline'
}

export function CheckListDisplayFromJSON(json: any): CheckListDisplay {
    return CheckListDisplayFromJSONTyped(json, false);
}

export function CheckListDisplayFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckListDisplay {
    return json as CheckListDisplay;
}

export function CheckListDisplayToJSON(value?: CheckListDisplay | null): any {
    return value as any;
}

