/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CheckListDisplay,
    CheckListDisplayFromJSON,
    CheckListDisplayFromJSONTyped,
    CheckListDisplayToJSON,
} from './';

/**
 * 
 * @export
 * @interface CheckListPrintingMetadata
 */
export interface CheckListPrintingMetadata {
    /**
     * 
     * @type {CheckListDisplay}
     * @memberof CheckListPrintingMetadata
     */
    display?: CheckListDisplay;
}

export function CheckListPrintingMetadataFromJSON(json: any): CheckListPrintingMetadata {
    return CheckListPrintingMetadataFromJSONTyped(json, false);
}

export function CheckListPrintingMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckListPrintingMetadata {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'display': !exists(json, 'display') ? undefined : CheckListDisplayFromJSON(json['display']),
    };
}

export function CheckListPrintingMetadataToJSON(value?: CheckListPrintingMetadata | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'display': CheckListDisplayToJSON(value.display),
    };
}


