/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CheckValue,
    CheckValueFromJSON,
    CheckValueFromJSONTyped,
    CheckValueToJSON,
} from './';

/**
 * 
 * @export
 * @interface CheckListItemDTO
 */
export interface CheckListItemDTO {
    /**
     * 
     * @type {number}
     * @memberof CheckListItemDTO
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CheckListItemDTO
     */
    checkListId?: number;
    /**
     * 
     * @type {string}
     * @memberof CheckListItemDTO
     */
    text?: string | null;
    /**
     * 
     * @type {CheckValue}
     * @memberof CheckListItemDTO
     */
    checked?: CheckValue;
    /**
     * 
     * @type {boolean}
     * @memberof CheckListItemDTO
     */
    editable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CheckListItemDTO
     */
    required?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CheckListItemDTO
     */
    remarks?: string | null;
}

export function CheckListItemDTOFromJSON(json: any): CheckListItemDTO {
    return CheckListItemDTOFromJSONTyped(json, false);
}

export function CheckListItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckListItemDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'checkListId': !exists(json, 'checkListId') ? undefined : json['checkListId'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'checked': !exists(json, 'checked') ? undefined : CheckValueFromJSON(json['checked']),
        'editable': !exists(json, 'editable') ? undefined : json['editable'],
        'required': !exists(json, 'required') ? undefined : json['required'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
    };
}

export function CheckListItemDTOToJSON(value?: CheckListItemDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'checkListId': value.checkListId,
        'text': value.text,
        'checked': CheckValueToJSON(value.checked),
        'editable': value.editable,
        'required': value.required,
        'remarks': value.remarks,
    };
}


