/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Section,
    SectionFromJSON,
    SectionFromJSONTyped,
    SectionToJSON,
} from './';

/**
 * 
 * @export
 * @interface CostSheet
 */
export interface CostSheet {
    /**
     * 
     * @type {number}
     * @memberof CostSheet
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CostSheet
     */
    project?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CostSheet
     */
    location?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CostSheet
     */
    dateCreated?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof CostSheet
     */
    materialMarkup?: number;
    /**
     * 
     * @type {number}
     * @memberof CostSheet
     */
    labourDailyRate?: number;
    /**
     * 
     * @type {number}
     * @memberof CostSheet
     */
    labourNightMultiplier?: number;
    /**
     * 
     * @type {number}
     * @memberof CostSheet
     */
    finalMarkup?: number;
    /**
     * 
     * @type {Array<Section>}
     * @memberof CostSheet
     */
    sections?: Array<Section> | null;
    /**
     * 
     * @type {Date}
     * @memberof CostSheet
     */
    lastUpdate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof CostSheet
     */
    updated?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof CostSheet
     */
    lastEdit?: Date;
    /**
     * 
     * @type {string}
     * @memberof CostSheet
     */
    lastEditUser?: string | null;
}

export function CostSheetFromJSON(json: any): CostSheet {
    return CostSheetFromJSONTyped(json, false);
}

export function CostSheetFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostSheet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'project': !exists(json, 'project') ? undefined : json['project'],
        'location': !exists(json, 'location') ? undefined : json['location'],
        'dateCreated': !exists(json, 'dateCreated') ? undefined : (json['dateCreated'] === null ? null : new Date(json['dateCreated'])),
        'materialMarkup': !exists(json, 'materialMarkup') ? undefined : json['materialMarkup'],
        'labourDailyRate': !exists(json, 'labourDailyRate') ? undefined : json['labourDailyRate'],
        'labourNightMultiplier': !exists(json, 'labourNightMultiplier') ? undefined : json['labourNightMultiplier'],
        'finalMarkup': !exists(json, 'finalMarkup') ? undefined : json['finalMarkup'],
        'sections': !exists(json, 'sections') ? undefined : (json['sections'] === null ? null : (json['sections'] as Array<any>).map(SectionFromJSON)),
        'lastUpdate': !exists(json, 'lastUpdate') ? undefined : (json['lastUpdate'] === null ? null : new Date(json['lastUpdate'])),
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'lastEdit': !exists(json, 'lastEdit') ? undefined : (new Date(json['lastEdit'])),
        'lastEditUser': !exists(json, 'lastEditUser') ? undefined : json['lastEditUser'],
    };
}

export function CostSheetToJSON(value?: CostSheet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'project': value.project,
        'location': value.location,
        'dateCreated': value.dateCreated === undefined ? undefined : (value.dateCreated === null ? null : value.dateCreated.toISOString()),
        'materialMarkup': value.materialMarkup,
        'labourDailyRate': value.labourDailyRate,
        'labourNightMultiplier': value.labourNightMultiplier,
        'finalMarkup': value.finalMarkup,
        'sections': value.sections === undefined ? undefined : (value.sections === null ? null : (value.sections as Array<any>).map(SectionToJSON)),
        'lastUpdate': value.lastUpdate === undefined ? undefined : (value.lastUpdate === null ? null : value.lastUpdate.toISOString()),
        'updated': value.updated,
        'lastEdit': value.lastEdit === undefined ? undefined : (value.lastEdit.toISOString()),
        'lastEditUser': value.lastEditUser,
    };
}


