/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrentTable
 */
export interface CurrentTable {
    /**
     * 
     * @type {number}
     * @memberof CurrentTable
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CurrentTable
     */
    circuit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentTable
     */
    startDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentTable
     */
    endDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CurrentTable
     */
    currentData?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof CurrentTable
     */
    lastEdit?: Date;
    /**
     * 
     * @type {string}
     * @memberof CurrentTable
     */
    lastEditUser?: string | null;
}

export function CurrentTableFromJSON(json: any): CurrentTable {
    return CurrentTableFromJSONTyped(json, false);
}

export function CurrentTableFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrentTable {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'circuit': !exists(json, 'circuit') ? undefined : json['circuit'],
        'startDate': !exists(json, 'startDate') ? undefined : json['startDate'],
        'endDate': !exists(json, 'endDate') ? undefined : json['endDate'],
        'currentData': !exists(json, 'currentData') ? undefined : json['currentData'],
        'lastEdit': !exists(json, 'lastEdit') ? undefined : (new Date(json['lastEdit'])),
        'lastEditUser': !exists(json, 'lastEditUser') ? undefined : json['lastEditUser'],
    };
}

export function CurrentTableToJSON(value?: CurrentTable | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'circuit': value.circuit,
        'startDate': value.startDate,
        'endDate': value.endDate,
        'currentData': value.currentData,
        'lastEdit': value.lastEdit === undefined ? undefined : (value.lastEdit.toISOString()),
        'lastEditUser': value.lastEditUser,
    };
}


