/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateTimeRange
 */
export interface DateTimeRange {
    /**
     * 
     * @type {Date}
     * @memberof DateTimeRange
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof DateTimeRange
     */
    end?: Date;
}

export function DateTimeRangeFromJSON(json: any): DateTimeRange {
    return DateTimeRangeFromJSONTyped(json, false);
}

export function DateTimeRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateTimeRange {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': !exists(json, 'start') ? undefined : (new Date(json['start'])),
        'end': !exists(json, 'end') ? undefined : (new Date(json['end'])),
    };
}

export function DateTimeRangeToJSON(value?: DateTimeRange | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start === undefined ? undefined : (value.start.toISOString()),
        'end': value.end === undefined ? undefined : (value.end.toISOString()),
    };
}


