/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DynamicFieldMetadata,
    DynamicFieldMetadataFromJSON,
    DynamicFieldMetadataFromJSONTyped,
    DynamicFieldMetadataToJSON,
} from './';

/**
 * 
 * @export
 * @interface DynamicFields
 */
export interface DynamicFields {
    /**
     * 
     * @type {Array<DynamicFieldMetadata>}
     * @memberof DynamicFields
     */
    fieldsDefinitions?: Array<DynamicFieldMetadata> | null;
}

export function DynamicFieldsFromJSON(json: any): DynamicFields {
    return DynamicFieldsFromJSONTyped(json, false);
}

export function DynamicFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DynamicFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fieldsDefinitions': !exists(json, 'fieldsDefinitions') ? undefined : (json['fieldsDefinitions'] === null ? null : (json['fieldsDefinitions'] as Array<any>).map(DynamicFieldMetadataFromJSON)),
    };
}

export function DynamicFieldsToJSON(value?: DynamicFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fieldsDefinitions': value.fieldsDefinitions === undefined ? undefined : (value.fieldsDefinitions === null ? null : (value.fieldsDefinitions as Array<any>).map(DynamicFieldMetadataToJSON)),
    };
}


