/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditPhotoRecordCommand
 */
export interface EditPhotoRecordCommand {
    /**
     * 
     * @type {number}
     * @memberof EditPhotoRecordCommand
     */
    reportId?: number;
    /**
     * 
     * @type {number}
     * @memberof EditPhotoRecordCommand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EditPhotoRecordCommand
     */
    label?: string | null;
}

export function EditPhotoRecordCommandFromJSON(json: any): EditPhotoRecordCommand {
    return EditPhotoRecordCommandFromJSONTyped(json, false);
}

export function EditPhotoRecordCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditPhotoRecordCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportId': !exists(json, 'reportId') ? undefined : json['reportId'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'label': !exists(json, 'label') ? undefined : json['label'],
    };
}

export function EditPhotoRecordCommandToJSON(value?: EditPhotoRecordCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportId': value.reportId,
        'id': value.id,
        'label': value.label,
    };
}


