/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditNoteCommand
 */
export interface EditNoteCommand {
    /**
     * 
     * @type {number}
     * @memberof EditNoteCommand
     */
    reportId?: number;
    /**
     * 
     * @type {number}
     * @memberof EditNoteCommand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EditNoteCommand
     */
    text?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof EditNoteCommand
     */
    checked?: boolean;
}

export function EditNoteCommandFromJSON(json: any): EditNoteCommand {
    return EditNoteCommandFromJSONTyped(json, false);
}

export function EditNoteCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditNoteCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'reportId': !exists(json, 'reportId') ? undefined : json['reportId'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'checked': !exists(json, 'checked') ? undefined : json['checked'],
    };
}

export function EditNoteCommandToJSON(value?: EditNoteCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reportId': value.reportId,
        'id': value.id,
        'text': value.text,
        'checked': value.checked,
    };
}


