/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResponsibleType,
    ResponsibleTypeFromJSON,
    ResponsibleTypeFromJSONTyped,
    ResponsibleTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EditSignatureCommand
 */
export interface EditSignatureCommand {
    /**
     * 
     * @type {number}
     * @memberof EditSignatureCommand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EditSignatureCommand
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditSignatureCommand
     */
    annotation?: string | null;
    /**
     * 
     * @type {ResponsibleType}
     * @memberof EditSignatureCommand
     */
    responsibleType?: ResponsibleType;
    /**
     * 
     * @type {string}
     * @memberof EditSignatureCommand
     */
    responsibleName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditSignatureCommand
     */
    designation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditSignatureCommand
     */
    remarks?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EditSignatureCommand
     */
    date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof EditSignatureCommand
     */
    principal?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EditSignatureCommand
     */
    drawnSign?: string | null;
    /**
     * 
     * @type {number}
     * @memberof EditSignatureCommand
     */
    order?: number;
}

export function EditSignatureCommandFromJSON(json: any): EditSignatureCommand {
    return EditSignatureCommandFromJSONTyped(json, false);
}

export function EditSignatureCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditSignatureCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'responsibleType': !exists(json, 'responsibleType') ? undefined : ResponsibleTypeFromJSON(json['responsibleType']),
        'responsibleName': !exists(json, 'responsibleName') ? undefined : json['responsibleName'],
        'designation': !exists(json, 'designation') ? undefined : json['designation'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'drawnSign': !exists(json, 'drawnSign') ? undefined : json['drawnSign'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function EditSignatureCommandToJSON(value?: EditSignatureCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'annotation': value.annotation,
        'responsibleType': ResponsibleTypeToJSON(value.responsibleType),
        'responsibleName': value.responsibleName,
        'designation': value.designation,
        'remarks': value.remarks,
        'date': value.date === undefined ? undefined : (value.date.toISOString()),
        'principal': value.principal,
        'drawnSign': value.drawnSign,
        'order': value.order,
    };
}


