/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    itemNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Item
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    materialMarkup?: number;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    noCables?: number;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    unitCost?: number;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    units?: number;
    /**
     * 
     * @type {number}
     * @memberof Item
     */
    labourCostUnit?: number;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemNumber': !exists(json, 'itemNumber') ? undefined : json['itemNumber'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'materialMarkup': !exists(json, 'materialMarkup') ? undefined : json['materialMarkup'],
        'noCables': !exists(json, 'noCables') ? undefined : json['noCables'],
        'unitCost': !exists(json, 'unitCost') ? undefined : json['unitCost'],
        'units': !exists(json, 'units') ? undefined : json['units'],
        'labourCostUnit': !exists(json, 'labourCostUnit') ? undefined : json['labourCostUnit'],
    };
}

export function ItemToJSON(value?: Item | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'itemNumber': value.itemNumber,
        'description': value.description,
        'materialMarkup': value.materialMarkup,
        'noCables': value.noCables,
        'unitCost': value.unitCost,
        'units': value.units,
        'labourCostUnit': value.labourCostUnit,
    };
}


