/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewAddressDto
 */
export interface NewAddressDto {
    /**
     * 
     * @type {number}
     * @memberof NewAddressDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NewAddressDto
     */
    addressLine?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewAddressDto
     */
    addressLine2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewAddressDto
     */
    unit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewAddressDto
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NewAddressDto
     */
    postalCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NewAddressDto
     */
    licenseId?: number;
}

export function NewAddressDtoFromJSON(json: any): NewAddressDto {
    return NewAddressDtoFromJSONTyped(json, false);
}

export function NewAddressDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewAddressDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'addressLine': !exists(json, 'addressLine') ? undefined : json['addressLine'],
        'addressLine2': !exists(json, 'addressLine2') ? undefined : json['addressLine2'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'postalCode': !exists(json, 'postalCode') ? undefined : json['postalCode'],
        'licenseId': !exists(json, 'licenseId') ? undefined : json['licenseId'],
    };
}

export function NewAddressDtoToJSON(value?: NewAddressDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'addressLine': value.addressLine,
        'addressLine2': value.addressLine2,
        'unit': value.unit,
        'country': value.country,
        'postalCode': value.postalCode,
        'licenseId': value.licenseId,
    };
}


