/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Options
 */
export interface Options {
    /**
     * 
     * @type {number}
     * @memberof Options
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Options
     */
    scheduleWeeks?: number;
    /**
     * 
     * @type {number}
     * @memberof Options
     */
    autosaveInterval?: number;
    /**
     * 
     * @type {Date}
     * @memberof Options
     */
    lastUpdate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Options
     */
    lastEdit?: Date;
    /**
     * 
     * @type {string}
     * @memberof Options
     */
    lastEditUser?: string | null;
}

export function OptionsFromJSON(json: any): Options {
    return OptionsFromJSONTyped(json, false);
}

export function OptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Options {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'scheduleWeeks': !exists(json, 'scheduleWeeks') ? undefined : json['scheduleWeeks'],
        'autosaveInterval': !exists(json, 'autosaveInterval') ? undefined : json['autosaveInterval'],
        'lastUpdate': !exists(json, 'lastUpdate') ? undefined : (new Date(json['lastUpdate'])),
        'lastEdit': !exists(json, 'lastEdit') ? undefined : (new Date(json['lastEdit'])),
        'lastEditUser': !exists(json, 'lastEditUser') ? undefined : json['lastEditUser'],
    };
}

export function OptionsToJSON(value?: Options | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'scheduleWeeks': value.scheduleWeeks,
        'autosaveInterval': value.autosaveInterval,
        'lastUpdate': value.lastUpdate === undefined ? undefined : (value.lastUpdate.toISOString()),
        'lastEdit': value.lastEdit === undefined ? undefined : (value.lastEdit.toISOString()),
        'lastEditUser': value.lastEditUser,
    };
}


