/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Job,
    JobFromJSON,
    JobFromJSONTyped,
    JobToJSON,
    Options,
    OptionsFromJSON,
    OptionsFromJSONTyped,
    OptionsToJSON,
    SchedJob,
    SchedJobFromJSON,
    SchedJobFromJSONTyped,
    SchedJobToJSON,
    Team,
    TeamFromJSON,
    TeamFromJSONTyped,
    TeamToJSON,
} from './';

/**
 * 
 * @export
 * @interface ScheduleData
 */
export interface ScheduleData {
    /**
     * 
     * @type {Date}
     * @memberof ScheduleData
     */
    lastUpdate?: Date | null;
    /**
     * 
     * @type {Array<Job>}
     * @memberof ScheduleData
     */
    jobs?: Array<Job> | null;
    /**
     * 
     * @type {Array<SchedJob>}
     * @memberof ScheduleData
     */
    schedJobs?: Array<SchedJob> | null;
    /**
     * 
     * @type {Array<Team>}
     * @memberof ScheduleData
     */
    teams?: Array<Team> | null;
    /**
     * 
     * @type {Options}
     * @memberof ScheduleData
     */
    options?: Options;
    /**
     * 
     * @type {string}
     * @memberof ScheduleData
     */
    apiVersion?: string | null;
}

export function ScheduleDataFromJSON(json: any): ScheduleData {
    return ScheduleDataFromJSONTyped(json, false);
}

export function ScheduleDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScheduleData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lastUpdate': !exists(json, 'lastUpdate') ? undefined : (json['lastUpdate'] === null ? null : new Date(json['lastUpdate'])),
        'jobs': !exists(json, 'jobs') ? undefined : (json['jobs'] === null ? null : (json['jobs'] as Array<any>).map(JobFromJSON)),
        'schedJobs': !exists(json, 'schedJobs') ? undefined : (json['schedJobs'] === null ? null : (json['schedJobs'] as Array<any>).map(SchedJobFromJSON)),
        'teams': !exists(json, 'teams') ? undefined : (json['teams'] === null ? null : (json['teams'] as Array<any>).map(TeamFromJSON)),
        'options': !exists(json, 'options') ? undefined : OptionsFromJSON(json['options']),
        'apiVersion': !exists(json, 'apiVersion') ? undefined : json['apiVersion'],
    };
}

export function ScheduleDataToJSON(value?: ScheduleData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lastUpdate': value.lastUpdate === undefined ? undefined : (value.lastUpdate === null ? null : value.lastUpdate.toISOString()),
        'jobs': value.jobs === undefined ? undefined : (value.jobs === null ? null : (value.jobs as Array<any>).map(JobToJSON)),
        'schedJobs': value.schedJobs === undefined ? undefined : (value.schedJobs === null ? null : (value.schedJobs as Array<any>).map(SchedJobToJSON)),
        'teams': value.teams === undefined ? undefined : (value.teams === null ? null : (value.teams as Array<any>).map(TeamToJSON)),
        'options': OptionsToJSON(value.options),
        'apiVersion': value.apiVersion,
    };
}


