/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Item,
    ItemFromJSON,
    ItemFromJSONTyped,
    ItemToJSON,
} from './';

/**
 * 
 * @export
 * @interface Section
 */
export interface Section {
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    secNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    subSection?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Section
     */
    description?: string | null;
    /**
     * 
     * @type {Array<Item>}
     * @memberof Section
     */
    items?: Array<Item> | null;
    /**
     * 
     * @type {number}
     * @memberof Section
     */
    materialMarkup?: number;
    /**
     * 
     * @type {number}
     * @memberof Section
     */
    finalMarkup?: number;
}

export function SectionFromJSON(json: any): Section {
    return SectionFromJSONTyped(json, false);
}

export function SectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Section {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'secNumber': !exists(json, 'secNumber') ? undefined : json['secNumber'],
        'subSection': !exists(json, 'subSection') ? undefined : json['subSection'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(ItemFromJSON)),
        'materialMarkup': !exists(json, 'materialMarkup') ? undefined : json['materialMarkup'],
        'finalMarkup': !exists(json, 'finalMarkup') ? undefined : json['finalMarkup'],
    };
}

export function SectionToJSON(value?: Section | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'secNumber': value.secNumber,
        'subSection': value.subSection,
        'description': value.description,
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(ItemToJSON)),
        'materialMarkup': value.materialMarkup,
        'finalMarkup': value.finalMarkup,
    };
}


