/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ResponsibleType,
    ResponsibleTypeFromJSON,
    ResponsibleTypeFromJSONTyped,
    ResponsibleTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface SignatureDto
 */
export interface SignatureDto {
    /**
     * 
     * @type {number}
     * @memberof SignatureDto
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof SignatureDto
     */
    readonly title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignatureDto
     */
    readonly annotation?: string | null;
    /**
     * 
     * @type {ResponsibleType}
     * @memberof SignatureDto
     */
    responsableType?: ResponsibleType;
    /**
     * 
     * @type {string}
     * @memberof SignatureDto
     */
    readonly responsableName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignatureDto
     */
    readonly designation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignatureDto
     */
    readonly remarks?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SignatureDto
     */
    readonly date?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SignatureDto
     */
    readonly principal?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SignatureDto
     */
    readonly reportId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SignatureDto
     */
    readonly reportConfigurationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SignatureDto
     */
    readonly order?: number;
}

export function SignatureDtoFromJSON(json: any): SignatureDto {
    return SignatureDtoFromJSONTyped(json, false);
}

export function SignatureDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'responsableType': !exists(json, 'responsableType') ? undefined : ResponsibleTypeFromJSON(json['responsableType']),
        'responsableName': !exists(json, 'responsableName') ? undefined : json['responsableName'],
        'designation': !exists(json, 'designation') ? undefined : json['designation'],
        'remarks': !exists(json, 'remarks') ? undefined : json['remarks'],
        'date': !exists(json, 'date') ? undefined : (new Date(json['date'])),
        'principal': !exists(json, 'principal') ? undefined : json['principal'],
        'reportId': !exists(json, 'reportId') ? undefined : json['reportId'],
        'reportConfigurationId': !exists(json, 'reportConfigurationId') ? undefined : json['reportConfigurationId'],
        'order': !exists(json, 'order') ? undefined : json['order'],
    };
}

export function SignatureDtoToJSON(value?: SignatureDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'responsableType': ResponsibleTypeToJSON(value.responsableType),
    };
}


