/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    vehicle?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    foreman?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Team
     */
    position?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Team
     */
    updated?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Team
     */
    lastUpdate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    teamMembers?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof Team
     */
    lastEdit?: Date;
    /**
     * 
     * @type {string}
     * @memberof Team
     */
    lastEditUser?: string | null;
}

export function TeamFromJSON(json: any): Team {
    return TeamFromJSONTyped(json, false);
}

export function TeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Team {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'vehicle': !exists(json, 'vehicle') ? undefined : json['vehicle'],
        'foreman': !exists(json, 'foreman') ? undefined : json['foreman'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'lastUpdate': !exists(json, 'lastUpdate') ? undefined : (json['lastUpdate'] === null ? null : new Date(json['lastUpdate'])),
        'teamMembers': !exists(json, 'teamMembers') ? undefined : json['teamMembers'],
        'lastEdit': !exists(json, 'lastEdit') ? undefined : (new Date(json['lastEdit'])),
        'lastEditUser': !exists(json, 'lastEditUser') ? undefined : json['lastEditUser'],
    };
}

export function TeamToJSON(value?: Team | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'vehicle': value.vehicle,
        'foreman': value.foreman,
        'position': value.position,
        'updated': value.updated,
        'lastUpdate': value.lastUpdate === undefined ? undefined : (value.lastUpdate === null ? null : value.lastUpdate.toISOString()),
        'teamMembers': value.teamMembers,
        'lastEdit': value.lastEdit === undefined ? undefined : (value.lastEdit.toISOString()),
        'lastEditUser': value.lastEditUser,
    };
}


