/* tslint:disable */
/* eslint-disable */
/**
 * Inspections API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCheckListCommand
 */
export interface UpdateCheckListCommand {
    /**
     * 
     * @type {number}
     * @memberof UpdateCheckListCommand
     */
    idCheckList?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateCheckListCommand
     */
    text?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateCheckListCommand
     */
    annotation?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateCheckListCommand
     */
    isConfiguration?: boolean;
}

export function UpdateCheckListCommandFromJSON(json: any): UpdateCheckListCommand {
    return UpdateCheckListCommandFromJSONTyped(json, false);
}

export function UpdateCheckListCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCheckListCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'idCheckList': !exists(json, 'idCheckList') ? undefined : json['idCheckList'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'annotation': !exists(json, 'annotation') ? undefined : json['annotation'],
        'isConfiguration': !exists(json, 'isConfiguration') ? undefined : json['isConfiguration'],
    };
}

export function UpdateCheckListCommandToJSON(value?: UpdateCheckListCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'idCheckList': value.idCheckList,
        'text': value.text,
        'annotation': value.annotation,
        'isConfiguration': value.isConfiguration,
    };
}


