// <auto-generated />
using System;
using System.Text.Json;
using Inspections.Core.Domain;
using Inspections.Core.Domain.ReportConfigurationAggregate;
using Inspections.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Inspections.Infrastructure.Data.Migrations
{
    [DbContext(typeof(InspectionsContext))]
    [Migration("20220608140630_add_costsheet_options_field")]
    partial class add_costsheet_options_field
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormDefinitionReportConfiguration", b =>
                {
                    b.Property<int>("FormsId")
                        .HasColumnType("integer");

                    b.Property<int>("ReportConfigurationsId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("FormsId", "ReportConfigurationsId");

                    b.HasIndex("ReportConfigurationsId");

                    b.ToTable("FormDefinitionReportConfiguration", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("Addresses", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CheckListAggregate.CheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfiguration")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ReportConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportConfigurationId");

                    b.HasIndex("ReportId");

                    b.ToTable("CheckLists", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CheckListAggregate.CheckListItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListId")
                        .HasColumnType("integer");

                    b.Property<int>("Checked")
                        .HasColumnType("integer");

                    b.Property<bool>("Editable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Touched")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CheckListId");

                    b.ToTable("CheckListItems", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CostSheet", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("finalMarkup")
                        .HasColumnType("double precision");

                    b.Property<bool>("isTemplate")
                        .HasColumnType("boolean");

                    b.Property<double>("labourDailyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("labourNightMultiplier")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("materialMarkup")
                        .HasColumnType("double precision");

                    b.Property<CSOptions>("options")
                        .HasColumnType("jsonb");

                    b.Property<string>("project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Section[]>("sections")
                        .HasColumnType("jsonb");

                    b.Property<bool>("updated")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("CostSheet");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CSTemplate", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("dateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("finalMarkup")
                        .HasColumnType("double precision");

                    b.Property<bool>("isTemplate")
                        .HasColumnType("boolean");

                    b.Property<double>("labourDailyRate")
                        .HasColumnType("double precision");

                    b.Property<double>("labourNightMultiplier")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("materialMarkup")
                        .HasColumnType("double precision");

                    b.Property<CSOptions>("options")
                        .HasColumnType("jsonb");

                    b.Property<string>("project")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Section[]>("sections")
                        .HasColumnType("jsonb");

                    b.Property<bool>("updated")
                        .HasColumnType("boolean");

                    b.HasKey("id");

                    b.ToTable("CSTemplate");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CurrentTable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("circuit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("currentData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("current_data");

                    b.Property<string>("endDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("end_date");

                    b.Property<string>("startDate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("start_date");

                    b.HasKey("id");

                    b.ToTable("current");
                });

            modelBuilder.Entity("Inspections.Core.Domain.EMALicense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amp")
                        .HasColumnType("numeric");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<decimal>("KVA")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonInCharge")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Volt")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Licenses", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.Forms.FormDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DynamicFields>("Fields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{ \"FieldsDefinitions\": null }'::jsonb");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("FormDefinition", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.Job", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("comments")
                        .HasColumnType("text");

                    b.Property<string>("duration")
                        .HasColumnType("text");

                    b.Property<DateTime?>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("priority")
                        .HasColumnType("integer");

                    b.Property<string>("salesPerson")
                        .HasColumnType("text");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.Property<string>("shift")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasColumnType("text");

                    b.Property<string>("tag")
                        .HasColumnType("text");

                    b.Property<string>("teamCount")
                        .HasColumnType("text");

                    b.Property<string>("teams")
                        .HasColumnType("text");

                    b.Property<string>("value")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Inspections.Core.Domain.Options", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("autosaveInterval")
                        .HasColumnType("integer");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("scheduleWeeks")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Inspections.Core.Domain.PrintSectionsAggregate.PrintSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMainReport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.ToTable("PrintSections", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportConfigurationAggregate.ReportConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<CheckListPrintingMetadata>("CheckListMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{ \"Display\": 0 }'::jsonb");

                    b.Property<string>("Footer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Inactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("MarginBottom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarginLeft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarginRight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarginTop")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PrintSectionId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<string>("RemarksLabelText")
                        .HasColumnType("text");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("print");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReportsConfiguration", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Checked")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("NeedsCheck")
                        .HasColumnType("boolean");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Notes", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.PhotoRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileNameResized")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhotoStorageId")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("ThumbnailStorageId")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("Photos", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EMALicenseId")
                        .HasColumnType("integer");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemarksLabelText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportConfigurationId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EMALicenseId");

                    b.ToTable("Reports", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.ReportForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DynamicFields>("Fields")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'{ \"FieldsDefinitions\": null }'::jsonb");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<int>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<JsonDocument>("Values")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportFroms", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.SchedJob", b =>
                {
                    b.Property<int>("team")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("excludeSaturday")
                        .HasColumnType("boolean");

                    b.Property<bool>("excludeSunday")
                        .HasColumnType("boolean");

                    b.Property<int>("id")
                        .HasColumnType("integer");

                    b.Property<string>("job1")
                        .HasColumnType("text");

                    b.Property<string>("job2")
                        .HasColumnType("text");

                    b.Property<DateTime?>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("shift")
                        .HasColumnType("text");

                    b.Property<bool>("splitShift")
                        .HasColumnType("boolean");

                    b.Property<string>("teamMembers")
                        .HasColumnType("text");

                    b.HasKey("team", "date");

                    b.ToTable("SchedJob");
                });

            modelBuilder.Entity("Inspections.Core.Domain.SignaturesAggregate.Signature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("DrawnSign")
                        .HasColumnType("text");

                    b.Property<bool>("IsConfiguration")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<short>("Order")
                        .HasColumnType("smallint");

                    b.Property<bool>("Principal")
                        .HasColumnType("boolean");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int?>("ReportConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ReportId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReportConfigurationId");

                    b.HasIndex("ReportId");

                    b.ToTable("Signatures", "Inspections");
                });

            modelBuilder.Entity("Inspections.Core.Domain.Team", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("foreman")
                        .HasColumnType("text");

                    b.Property<DateTime?>("lastUpdate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("position")
                        .HasColumnType("integer");

                    b.Property<string>("teamMembers")
                        .HasColumnType("text");

                    b.Property<string>("vehicle")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("Inspections.Core.Domain.Template", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("templateDef")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("Inspections.Core.Domain.User", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("LastEditedReport")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Inspections.Core.QueryModels.ResumenCheckList", b =>
                {
                    b.Property<string>("Annotation")
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer");

                    b.ToTable("ResumenCheckList", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("Inspections.Core.QueryModels.ResumenReportConfiguration", b =>
                {
                    b.Property<int>("DefinedCheckLists")
                        .HasColumnType("integer");

                    b.Property<int>("DefinedSignatures")
                        .HasColumnType("integer");

                    b.Property<string>("FormName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<bool>("Inactive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastEdit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastEditUser")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PrintSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemarksLabelText")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UsedByReports")
                        .HasColumnType("integer");

                    b.ToTable("ResumenReportConfiguration", null, t => t.ExcludeFromMigrations());
                });

            modelBuilder.Entity("FormDefinitionReportConfiguration", b =>
                {
                    b.HasOne("Inspections.Core.Domain.Forms.FormDefinition", null)
                        .WithMany()
                        .HasForeignKey("FormsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Inspections.Core.Domain.ReportConfigurationAggregate.ReportConfiguration", null)
                        .WithMany()
                        .HasForeignKey("ReportConfigurationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.Address", b =>
                {
                    b.HasOne("Inspections.Core.Domain.EMALicense", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CheckListAggregate.CheckList", b =>
                {
                    b.HasOne("Inspections.Core.Domain.ReportConfigurationAggregate.ReportConfiguration", "ReportConfiguration")
                        .WithMany("ChecksDefinition")
                        .HasForeignKey("ReportConfigurationId");

                    b.HasOne("Inspections.Core.Domain.ReportsAggregate.Report", "Report")
                        .WithMany("CheckList")
                        .HasForeignKey("ReportId");

                    b.Navigation("Report");

                    b.Navigation("ReportConfiguration");
                });

            modelBuilder.Entity("Inspections.Core.Domain.CheckListAggregate.CheckListItem", b =>
                {
                    b.HasOne("Inspections.Core.Domain.CheckListAggregate.CheckList", null)
                        .WithMany("Checks")
                        .HasForeignKey("CheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.EMALicense", b =>
                {
                    b.OwnsOne("Inspections.Shared.DateTimeRange", "Validity", b1 =>
                        {
                            b1.Property<int>("EMALicenseId")
                                .HasColumnType("integer");

                            b1.Property<DateTime>("End")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<DateTime>("Start")
                                .HasColumnType("timestamp without time zone");

                            b1.HasKey("EMALicenseId");

                            b1.ToTable("Licenses", "Inspections");

                            b1.WithOwner()
                                .HasForeignKey("EMALicenseId");
                        });

                    b.Navigation("Validity")
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.Note", b =>
                {
                    b.HasOne("Inspections.Core.Domain.ReportsAggregate.Report", null)
                        .WithMany("Notes")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.PhotoRecord", b =>
                {
                    b.HasOne("Inspections.Core.Domain.ReportsAggregate.Report", null)
                        .WithMany("PhotoRecords")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.Report", b =>
                {
                    b.HasOne("Inspections.Core.Domain.EMALicense", "License")
                        .WithMany()
                        .HasForeignKey("EMALicenseId");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.ReportForm", b =>
                {
                    b.HasOne("Inspections.Core.Domain.ReportsAggregate.Report", null)
                        .WithMany("AvailableForms")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.SignaturesAggregate.Signature", b =>
                {
                    b.HasOne("Inspections.Core.Domain.ReportConfigurationAggregate.ReportConfiguration", null)
                        .WithMany("SignatureDefinitions")
                        .HasForeignKey("ReportConfigurationId");

                    b.HasOne("Inspections.Core.Domain.ReportsAggregate.Report", null)
                        .WithMany("Signatures")
                        .HasForeignKey("ReportId");

                    b.OwnsOne("Inspections.Core.Domain.SignaturesAggregate.Responsible", "Responsible", b1 =>
                        {
                            b1.Property<int>("SignatureId")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Type")
                                .HasColumnType("integer");

                            b1.HasKey("SignatureId");

                            b1.ToTable("Signatures", "Inspections");

                            b1.WithOwner()
                                .HasForeignKey("SignatureId");
                        });

                    b.Navigation("Responsible")
                        .IsRequired();
                });

            modelBuilder.Entity("Inspections.Core.Domain.CheckListAggregate.CheckList", b =>
                {
                    b.Navigation("Checks");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportConfigurationAggregate.ReportConfiguration", b =>
                {
                    b.Navigation("ChecksDefinition");

                    b.Navigation("SignatureDefinitions");
                });

            modelBuilder.Entity("Inspections.Core.Domain.ReportsAggregate.Report", b =>
                {
                    b.Navigation("AvailableForms");

                    b.Navigation("CheckList");

                    b.Navigation("Notes");

                    b.Navigation("PhotoRecords");

                    b.Navigation("Signatures");
                });
#pragma warning restore 612, 618
        }
    }
}
