name: Docker Image CI

on:
  push:
    tags:
      - test-*
      - prod-*
jobs:

  build-backend:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: ${{ env.RELEASE_VERSION }}
          separator: '-'
          limit: 3

      - name: version to env
        run: |
          echo "BRANCH=${{ steps.split.outputs._0 }}" >> $GITHUB_ENV
          echo "RELEASE_DATE=${{ steps.split.outputs._1 }}" >> $GITHUB_ENV
          echo "REVISION=${{ steps.split.outputs._2 }}" >> $GITHUB_ENV
      
      - name: Docker hub Login
        env:
          DOCKER_USER: ${{secrets.IOSOFT_DOCKERHUB_USER}}
          DOCKER_PASSWORD: ${{secrets.IOSOFT_DOCKERHUB_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build backend
        run: |
          echo ${{ env.BRANCH }}
          echo ${{ env.RELEASE_DATE }}
          echo ${{ env.REVISION }}
          docker build src/Backend --file src/Backend/Dockerfile --tag $DOCKER_USER/scb-backend:${{env.BRANCH}}
          
      - name: Build Frontend
        run: |
          echo ${{ env.BRANCH }}
          echo ${{ env.RELEASE_DATE }}
          echo ${{ env.REVISION }}
          docker build src/ClientApp --file src/ClientApp/Dockerfile --tag $DOCKER_USER/scb-frontend:${{env.BRANCH}}
      
      - name: Publish to docker hub
        env:
            DOCKER_USER: ${{secrets.IOSOFT_DOCKERHUB_USER}}
        run: |
          echo ${{ env.BRANCH }}
          echo ${{ env.RELEASE_DATE }}
          echo ${{ env.REVISION }}
          docker push $DOCKER_USER/scb-frontend
