name: Docker Image CI

on:
  push:
    tags:
      - test-*
      - prod-*
jobs:

  build-backend:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Split version code
        uses: xom9ikk/split@v1
        id: split
        with:
          string: test-2021-6 #${{ env.RELEASE_VERSION }}
          separator: \-
          limit: -1

      - name: Build the API Docker image
        with:
          release_branch: ${{ steps.split.outputs._0 }}
          release_date: ${{ steps.split.outputs._1 }}
          revision: ${{ steps.split.outputs._2 }}
        run : |
          echo $release_branch
          echo $release_date
          echo $revision
          docker build src/Backend --file src/Backend/Dockerfile --tag scb-backend:$release_branch      
