name: Docker Image CI

on:
  push:
    tags:
      - test-*
      - prod-*
jobs:

  build-backend:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - name: Get the tag name
          run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          
      - uses: actions/checkout@v2
      - name: Build the API Docker image
        run: docker build src/Backend --file Dockerfile --tag scb-backend:${{ env.TAG }}
