name: Docker Image CI

on:
  push:
    tags:
      - test-*
      - prod-*
jobs:

  build-backend:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v2
      - - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Build the API Docker image
        run: docker build src/Backend --file Dockerfile --tag scb-backend:${{ env.RELEASE_VERSION }}
