name: Inspections Dev Deploymentr

on:
  create:
    tags: 
    - dev-*

jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      working_directory: ./src/Backend/Inspections.API
  
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: ${{env.working_directory}}
      - name: Build
        run: dotnet build --no-restore --config Release
        working-directory: ${{env.working_directory}}
  
  build-client:
    runs-on: ubuntu-latest
    env:
      working_directory: ./src/ClientApp
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v1
    
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
#
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing NPM
      run: npm install

    - name: Building application
      run: npm run build

    - name: Generate deployment package
      run: zip -r deploy.zip * -x "**node_modules**"
